### ISSUE TITLE
Can't install add-in.

### ISSUE THREAD

**Issue by amatkivskiy** [matthew-ch-robbins/xamarin-android-string-extractor#1]
Can't install add-in in Xamarin Studio (Alpha).

![addininstallfailed](https://cloud.githubusercontent.com/assets/3864884/8270360/03111de4-17e6-11e5-9c27-8d2c0642a174.JPG)

How can I install that dependencies?

**Comment by matthew-ch-robbins** [comment]
It looks like some dependencies are being included that aren't needed for the plugin to work. An update for this will be coming shortly that will remove these stray dependency references.

**Comment by amatkivskiy** [comment]
I've already found references that are requires:
```<AddinReference Include="MonoDevelop.CSharpBinding" />
<AddinReference Include="MonoDevelop.Xamarin.Ide" />
 <AddinReference Include="MonoDevelop.Refactoring" />
<AddinReference Include="MonoDevelop.MonoAndroid" />```

**Comment by matthew-ch-robbins** [comment]
Yep, just pushed a fix. The next release will be out soon.

**Comment by matthew-ch-robbins** [comment]
@amatkivskiy Version 0.0.2 should now be available through the addins dialog in Xamarin Studio. Please refresh the repositories and then install the latest version.
